### ISSUE TITLE
Sandbox severely cripples the host (24H2)

### ISSUE THREAD

**Issue by m33ts4k0z** [DuoStream/Duo#164]
A lot of trial and error since the release of 1.4.9. Latest findings are that installing the dependencies of sandbox, practically destroys the host. At least on 24H2. This is tried on a clean win11 24h2 installation.

A lof of bugs are happening: 

- Can no longer go to Windows Update, the button at the top right corner of the dashboard does nothing when clicked. I havent found any other way to get to the Windows Update either.
- The Apps settings menu is missing a lot of submenus like installed apps and these menus are no longer accessible by other means.
- System restore no longer works. It shows an "unsuccessful" error uppon restarting and the host shows black screen after login screen.
- PC reset while keeping personal files or clean wipe doesnt work. the issues persist even after successfully reseting the PC. 
- Display settings menu is gone. No way to open it.
- No Windows account can be created.

I will update this post with new findings but this already makes 1.4.9 unusable.

**Comment by m33ts4k0z** [comment]
I tried a total format again and reinstallled Win 11 Pro with 24H2 and then Duo 1.4.9 both on bare metal as well as inan Unraid VM. The behavior I described is very consistent in both cases.

**Comment by Black-Seraph** [comment]
I had leftover 23H2 files in my system, which is why this worked on my system.
I can confirm that clean 24H2 installs will **not work** with Duo's **Run in Sandbox** setting yet.

I'll close this issue for now as I already know what the issue is and what needs to be done, and because I'd like to keep discussion of this 24H2 regression in a single issue, if possible.

For those adventurous enough, you can transplant a recent enough 23H2 madrid.dll file into a 24H2 install and it will work somewhat, but I don't suggest it.

Instead, keep an eye on issue #165, which will serve as a list of pending to-dos to undo the damage Microsoft has done with 24H2.

**Comment by m33ts4k0z** [comment]
Thanks for looking into this 😊. I just tried formatting a 3rd time now but the same thing happens. Example image. The windows update entry had to be where the red rectangle is. Also notice the apps entries missing

![Screenshot 2024-10-06 220022](https://github.com/user-attachments/assets/1458c617-26bb-4339-973b-90ad777e85c7)

I used the 24H2 iso that I got using Rufus and fully updated it. I then formatted using a USB drive with Ventoy.

I got all updates for Windows but I noticed now that I don't have all the drivers for my motherboard's devices (aka I have triangles and unknown devices in the device manager). Do you think this could potentially be the problem?

Some notes: When you tried, did you perform these steps?

- Clean install, formatting the drive and not reseting or upgrading.
- Updated Windows to the latest updates.
- Restarted the PC after installing Duo 1.4.9.

The issue started after restarting when I installed Duo. I was able to run Duo normally before the restart. Basically Duo installed all the dependencies and then it installed itself. That is that I didn't have to re-run the installer after restarting as the message at the end of the installation suggests.

Also what are your memory integrity/core isolation settings? Could this matter too?

Thanks again for diving into this directly 😊

**Comment by Black-Seraph** [comment]
Reopening this issue because I can now confirm this on one of my machines.
@m33ts4k0z This is the strangest thing ever...

**Comment by Black-Seraph** [comment]
I found the cause of this issue but I can't quite explain it.

It's essentially Windows choking on its own Windows Update packages, which breaks its whole App & Update catalog.

And because Duo enables a bunch of Windows Update packages as part of its setup we now have affected Windows versions showing this behavior.

Manually ejecting these packages from the Windows Update package catalog _fixes_ this issue, but because we **need** these packages we're now stuck in somewhat of a dilemma.

Here's how to purge these packages from the catalog, bringing the missing menus back:
1. Execute the following in an administrative command line:
`dism.exe /online /disable-feature /featurename:Containers-DisposableClientVM`
2. As part of this action you'll have to reboot your computer, do so.
3. Execute the following in an administrative command line:
`dir /b %SystemRoot%\servicing\Packages\*Containers*.mum >sandbox.txt`
`for /f %%i in ('findstr /i . sandbox.txt 2^>nul') do dism /online /norestart /remove-package:"%SystemRoot%\servicing\Packages\%%i"`
`del sandbox.txt`
4. Reboot the computer one last time, the missing menu points will be back afterwards.

Now I need to figure out how we can get these packages enabled without Windows choking on its own stuff.

**Comment by m33ts4k0z** [comment]
Apart from sandbox, there is really no need to use 1.4.9 so if you are on 24H2, just stay on 1.4.8 till these issues are resolved. 23H2 has no issues with sandbox/1.4.9 though.

**Comment by m33ts4k0z** [comment]
Thanks for the explanation. Makes perfect sense.

So to recap. Apart from the effort needed to reverse engineer the new dll that has absorbed the madrid.dll functionality, we still need a way to make the sandbox packages to co-exist in a 24H2 system because what the commands you posted do, is to remove them so that the system works correctly again. Is that correct?

**Comment by Black-Seraph** [comment]
The commands I've posted are only there to buy 24H2 users time until I address this issue fully in Duo version 1.5.0, and they're only there to get the system back into a fully working state after Windows choked on its own packages that Duo's setup enabled in the package catalog.

I've done some more research since then and found that the issue is that Windows caches older versions of the package metadata in C:\Windows\servicing\Packages.

This causes multiple versions of the same package to get enabled as part of Duo's setup, which then causes Windows to fail on parsing the available package list.

This should be avoidable by adding a LCU-version tag to the setup's package filter, so there goes one problem.

The next problem is that 24H2 further splits up the Sandbox files across multiple features.

Part of the files are stored in the DisposableVM packages, some in the UtilityVM packages, some more in the HyperV packages and the last bits in the WindowsDefenderApplicationGuard packages.

In versions prior to 24H2 these could all be pulled in simply by enabling the DisposableVM feature, on 24H2 we need to do all that explicitly.

**Comment by schaeuble7** [comment]
Any chance that you could make the previous version available for download again? Or will it not work regardless, if I'm using 24h2.

**Comment by m33ts4k0z** [comment]
> Any chance that you could make the previous version available for download again? Or will it not work regardless, if I'm using 24h2.

The previous version is still available for download on the release page and it will work fine with 24H2

**Comment by TioBundy** [comment]
Install Windows with a USB (like installs from 0) but over your actual Windows session, fix all problems caused by Duo 1.4.9.

I couldn't be more scared with this today, I didn't feel like starting from 0. I literally thought it was malware this duo, I didn't understand anything.

**Comment by nav1014** [comment]
> I found the cause of this issue but I can't quite explain it.
> 
> It's essentially Windows choking on its own Windows Update packages, which breaks its whole App & Update catalog.
> 
> And because Duo enables a bunch of Windows Update packages as part of its setup we now have affected Windows versions showing this behavior.
> 
> Manually ejecting these packages from the Windows Update package catalog _fixes_ this issue, but because we **need** these packages we're now stuck in somewhat of a dilemma.
> 
> Here's how to purge these packages from the catalog, bringing the missing menus back:
> 
> 1. Execute the following in an administrative command line:
>    `dism.exe /online /disable-feature /featurename:Containers-DisposableClientVM`
> 2. As part of this action you'll have to reboot your computer, do so.
> 3. Execute the following in an administrative command line:
>    `dir /b %SystemRoot%\servicing\Packages\*Containers*.mum >sandbox.txt`
>    `for /f %%i in ('findstr /i . sandbox.txt 2^>nul') do dism /online /norestart /remove-package:"%SystemRoot%\servicing\Packages\%%i"`
>    `del sandbox.txt`
> 4. Reboot the computer one last time, the missing menu points will be back afterwards.
> 
> Now I need to figure out how we can get these packages enabled without Windows choking on its own stuff.

took me a while to figure out, but i had to replace "%%i" with "%i" for command prompt instead of a batch file

**Comment by kiri11** [comment]
Maybe it's worth releasing 1.5.0 with optional sandbox install? And a huge disclaimer: if you have a fresh 24H2, don't select the option to install sandboxes! 
Or at least add to README this issue?
Thanks.

**Comment by m33ts4k0z** [comment]
> Maybe it's worth releasing 1.5.0 with optional sandbox install? And a huge disclaimer: if you have a fresh 24H2, don't select the option to install sandboxes! Or at least add to README this issue? Thanks.

If you are on 24H2, don't install 1.4.9 at all. It's its initial setup that causes the issues mentioned in the first post and not the actual activation of the sandbox. Stick to 1.4.8 for the time being.

**Comment by ducksdoquack** [comment]
> I found the cause of this issue but I can't quite explain it.
> 
> It's essentially Windows choking on its own Windows Update packages, which breaks its whole App & Update catalog.
> 
> And because Duo enables a bunch of Windows Update packages as part of its setup we now have affected Windows versions showing this behavior.
> 
> Manually ejecting these packages from the Windows Update package catalog _fixes_ this issue, but because we **need** these packages we're now stuck in somewhat of a dilemma.
> 
> Here's how to purge these packages from the catalog, bringing the missing menus back:
> 
> 1. Execute the following in an administrative command line:
>    `dism.exe /online /disable-feature /featurename:Containers-DisposableClientVM`
> 2. As part of this action you'll have to reboot your computer, do so.
> 3. Execute the following in an administrative command line:
>    `dir /b %SystemRoot%\servicing\Packages\*Containers*.mum >sandbox.txt`
>    `for /f %%i in ('findstr /i . sandbox.txt 2^>nul') do dism /online /norestart /remove-package:"%SystemRoot%\servicing\Packages\%%i"`
>    `del sandbox.txt`
> 4. Reboot the computer one last time, the missing menu points will be back afterwards.
> 
> Now I need to figure out how we can get these packages enabled without Windows choking on its own stuff.

Here is a working version of those scripts for powershell (point 3 of your solution) :

Get-ChildItem -Name C:\Windows\servicing\Packages\*Containers*.mum > sandbox.txt
Get-Content .\sandbox.txt | ForEach-Object {
    dism /online /norestart /remove-package:"C:\Windows\servicing\Packages\$_"
}

**Comment by HakkinDavid** [comment]
Here to confirm this issue was also present on my PC w/ 24H2. Glad to see there is a fix available.

> I couldn't be more scared with this today, I didn't feel like starting from 0. I literally thought it was malware this duo, I didn't understand anything.

I share the feeling lol. I didn't think of it as malware but as a software dev myself I thought "well... something really messed up!"

**Comment by CodeOfficer** [comment]
Soooo ... 24H2 user here and just finished installing 1.4.9 when I read this thread. Am I able to just uninstall 1.4.9 and then reinstall 1.4.8 in any way? Or do I have to jump through the steps above? I want to break as little as possible. 🙈

**Comment by kiri11** [comment]
>  Am I able to just uninstall 1.4.9 and then reinstall 1.4.8 in any way? Or do I have to jump through the steps above? I want to break as little as possible. 🙈

As far as I remember, 1.4.9 didn't even install and it already broke everything. So I couldn't uninstall it. But if you can, try it. If Windows Update still broken, then you have to follow the steps above.

**Comment by CodeOfficer** [comment]
I was able to resolve my issue with an ISO reinstall of windows 11. Not touching this again until1.5.0 :) nope nope nope

**Comment by Black-Seraph** [comment]
1.5.0 is all about solving this issue pretty much, and it does, but I'm still trying to figure out a clean way of actually fixing installs that got broken in the first place.

**Comment by Wacheee** [comment]
@Black-Seraph I have 23H2 with 1.4.9 and I have no problems yet. If my Windows update to 24H2 it will be broke my machine? what do you recommend me to do, or just wait to 1.5.0?

**Comment by schaeuble7** [comment]
Ignacio, your install should be alright. Black seraph installed duo, then
upgraded  their windows install after and didn't experience the issue.

**Comment by MadWizardDE** [comment]
@Black-Seraph If I may ask, what were the symptoms of the problem on your test machines, that you couldn't make go away? I executed the commands to clean up the broken packages, like you suggested earlier and the visible problems went away. Are there maybe some problems let that are not easily recognized?

**Comment by Black-Seraph** [comment]
The problems are more long-term, as in, broken follow-up updates, side-by-side store repairs failing, etc.

This one issue was the biggest unexpected foobar that has ever happened to me, and to this day I haven't found a way to retroactively repair affected systems.

I'm terribly sorry this one has happened, but thankfully the times of 1.4.8 are long past us now and all versions beyond that have been perfectly fine and safe to use.

In fact, the upcoming 1.5.3 build did away with a lot of the sandbox feature requirements simply because I no longer trust the rather large amount of dependencies that come with Microsoft's own sandbox feature pack.
