### ISSUE TITLE
Unable to start the service

### ISSUE THREAD

**Issue by Dark1886** [DuoStream/Duo#98]
I previously had Duo working, but at some point (and I'm unsure when) the service stopped functioning and I cannot access a webpage for Duo or the Sunshine Instance. I attempted to uninstall Duo, reboot, re-install, reboot and it still has the same behavior. 

![image](https://github.com/DuoStream/Duo/assets/64846241/c08223e0-aa9f-4d20-b2d1-7ce9ed481325)

Here is the attached Software Event Log (Only 2 entries) 
[Duo_Event_Logs.zip](https://github.com/DuoStream/Duo/files/14936016/Duo_Event_Logs.zip)

**Comment by StijnWolf** [comment]
I think this has to do with some type of windows update. It was working perfectly for the past few months up until today. 
I didn't update windows as far as I'm aware, but I'm experiencing the same issue.

When I got back home and logged into the host I got some annoying Microsoft pop-up about syncing my microsoft account or some dumb stuff.

Maybe they patched rdpwrapper?

**Comment by Dark1886** [comment]
It appears I did have an update installed as of today on My pc listed below. Although I'm not sure if that caused anything directly or just coincidance. 

`2024-04 Cumulative Update for Windows 11 Version 23H2 for x64-based Systems (KB5036893)`
`2024-04 Cumulative Update for .NET Framework 3.5 and 4.8.1 for Windows 11, version 23H2 for x64 (KB5036620)`

**Comment by Dark1886** [comment]
@StijnWolf I have found a fix for it here https://github.com/stascorp/rdpwrap/issues/2552. Updating the local RdpWrap.ini to add the section below should fix it. Although I haven't actually streamed with it yet. We will just need to wait for this to be merged upstream before it's fully compatible. 

```
[10.0.22621.3447]
SingleUserPatch.x64=1
SingleUserOffset.x64=C3F3
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1C2E5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=9D661
LocalOnlyCode.x64=jmpshort
SLInitHook.x64=1
SLInitOffset.x64=29ED0
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.22621.3447-SLInit]
bServerSku.x64=12BF50
bRemoteConnAllowed.x64=12BF64
bFUSEnabled.x64=12BF74
bAppServerAllowed.x64=12BF5C
bMultimonAllowed.x64=12BF68
lMaxUserSessions.x64=12BF54
ulMaxDebugSessions.x64=12BF70
bInitialized.x64=12BF4C
```

**Comment by namquang93** [comment]
Sorry, but how to apply this fix? I did find the RdpWrap.ini in C:\Program Files\RDP Wrapper folder but after adding the text above, Duo still can't start.

**Comment by loyejaotdiqr47123** [comment]
> 我在这里找到了修复程序 [stascorp/rdpwrap#2552](https://github.com/stascorp/rdpwrap/issues/2552)。更新本地RdpWrap.ini以添加以下部分应该可以修复它。虽然我还没有真正用它流式传输。我们只需要等待它被合并到上游，然后它就可以完全兼容了。
> 
> ```
> [10.0.22621.3447]
> SingleUserPatch.x64=1
> SingleUserOffset.x64=C3F3
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=1C2E5
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=9D661
> LocalOnlyCode.x64=jmpshort
> SLInitHook.x64=1
> SLInitOffset.x64=29ED0
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.22621.3447-SLInit]
> bServerSku.x64=12BF50
> bRemoteConnAllowed.x64=12BF64
> bFUSEnabled.x64=12BF74
> bAppServerAllowed.x64=12BF5C
> bMultimonAllowed.x64=12BF68
> lMaxUserSessions.x64=12BF54
> ulMaxDebugSessions.x64=12BF70
> bInitialized.x64=12BF4C
> ```
Duo's rdpwrap is automatically synced

**Comment by Dark1886** [comment]
> > 我在这里找到了修复程序 [stascorp/rdpwrap#2552](https://github.com/stascorp/rdpwrap/issues/2552)。更新本地RdpWrap.ini以添加以下部分应该可以修复它。虽然我还没有真正用它流式传输。我们只需要等待它被合并到上游，然后它就可以完全兼容了。
> > ```
> > [10.0.22621.3447]
> > SingleUserPatch.x64=1
> > SingleUserOffset.x64=C3F3
> > SingleUserCode.x64=Zero
> > DefPolicyPatch.x64=1
> > DefPolicyOffset.x64=1C2E5
> > DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> > LocalOnlyPatch.x64=1
> > LocalOnlyOffset.x64=9D661
> > LocalOnlyCode.x64=jmpshort
> > SLInitHook.x64=1
> > SLInitOffset.x64=29ED0
> > SLInitFunc.x64=New_CSLQuery_Initialize
> > 
> > [10.0.22621.3447-SLInit]
> > bServerSku.x64=12BF50
> > bRemoteConnAllowed.x64=12BF64
> > bFUSEnabled.x64=12BF74
> > bAppServerAllowed.x64=12BF5C
> > bMultimonAllowed.x64=12BF68
> > lMaxUserSessions.x64=12BF54
> > ulMaxDebugSessions.x64=12BF70
> > bInitialized.x64=12BF4C
> > ```
> 
> Duo's rdpwrap is automatically synced

It should be automatically synced, but there apparently was some delay either in this sync or somewhere upstream as it didn't see an updated file for me, although this is the first time I've seen this issue so I'm not going to worry about it.

**Comment by Dark1886** [comment]
> Sorry, but how to apply this fix? I did find the RdpWrap.ini in C:\Program Files\RDP Wrapper folder but after adding the text above, Duo still can't start.
> 
> Restart didn't help neither.

It's possible your version is slightly different (I'm not an expert in this subject unfortunately) so you should go to event viewer and see what the official error message is. 

`Event Viewer -> Windows Logs -> Application` and look for entries that have "duo" in the source column.

**Comment by namquang93** [comment]
> > Sorry, but how to apply this fix? I did find the RdpWrap.ini in C:\Program Files\RDP Wrapper folder but after adding the text above, Duo still can't start.
> > Restart didn't help neither.
> 
> EDIT: It may just work now as @loyejaotdiqr47123 updated the upstream repo to include the fix. If not, do the following. First make sure you're pointing to the correct RDPWrap.ini file, Mine was in the Duo folder location `C:\Program Files\Duo\RdpWrap.ini`
> 
> It's possible your version is slightly different (I'm not an expert in this subject unfortunately) so you should go to event viewer and see what the official error message is.
> 
> `Event Viewer -> Windows Logs -> Application` and look for entries that have "duo" in the source column.

hey thank you for the info. However Duo is still not working for me. Checking Event View log I found Duo's error message `Failed to apply the display driver patch for My-PC`

**Comment by Dark1886** [comment]
@namquang93 unfortunately I don't have any experience with that issue. Hopefully some previously closed issues have the information you need to fix that. Do you happen to have some sort of antivirus that is preventing that from being applied?

**Comment by laurorual** [comment]
im getting "rdpwrap.ini doesnt support termsrv.dll version 10.0.22621.3447 yet"
tried @Dark1886 solution but didn't work, also tried updating RPDWrap manually and didn't work
so sad

**Comment by namquang93** [comment]
Hey just FYI somehow it just started working again on my computer.

**Comment by kopiezzo** [comment]
You can make it read only so it won't get overwrittem, it will work until theres an update

**Comment by Neomac** [comment]
> You can make it read only so it won't get overwritten, it will work until theres an update

This did the trick for the "The GitHub-hosted RdpWrap.ini doesn't support termsrv.dll version 10.0.22621.3447 yet, checking again in 30 minutes". Thanks a lot!

**Comment by niallobr** [comment]
For me it's the same as #100. Updating RdpWrap.ini and making it read only allows the web interface to start but Sunshine still doesn't start
`Faulting application name: svchost.exe_TermService, version: 10.0.22621.1, time stamp: 0x6dc5c2a5
Faulting module name: rdpwrap.dll, version: 1.4.3.0, time stamp: 0x661579f8
Exception code: 0xc0000005
Fault offset: 0x00000000000027aa
Faulting process id: 0x0x29C8
Faulting application start time: 0x0x1DA8D91A9DFC325
Faulting application path: C:\Windows\System32\svchost.exe
Faulting module path: c:\program files\duo\rdpwrap.dll
Report Id: df07fbb0-42c3-4c0e-9257-431c39163cee
Faulting package full name: 
Faulting package-relative application ID: `
But it seems to be working for some people like @bigjam3? Does rdpwrap.dll need to be updated also?

**Comment by kopiezzo** [comment]
It's working for me but I'm really not sure if that's the correct workaround, it's possible that it breaks things. I think it's better to wait for an official update if it's not working for you

**Comment by Neomac** [comment]
Found the fix for the issue https://github.com/DuoStream/Duo/issues/100, the problem was that the RdpWrap.ini **ABSOLUTLY** need an empty new line at the end of the file to work (https://github.com/stascorp/rdpwrap/issues/1332#issuecomment-785119954).

Added it and made it read only did the trick for now :).

**Comment by Dark1886** [comment]
Deleted my RdpWrap.ini file and started Duo 1.43 and it pulled the correct file and worked as expected. Closing issue.
